# Site settings

title: juulio.com # Title of your site
description: > # this means to ignore newlines until "baseurl:"
  I write algorithmically determined computer generated artwork
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juulio.com" # the base hostname & protocol for your site

twitter_username:     juulio  # Replace this with your Twitter username
github_username:      juulio  # Replace this with your GitHub username
linkedin_username:    juliodelvalle  # Replace this with your LinkedIn username

# Build settings
markdown: kramdown

# Experiments folder listing
collections:
  experiments:
    output: true
