# Site settings
title: juulio
description: > # this means to ignore newlines until "baseurl:"
  Costa Rica.<br />Software developer.<br />Computer Graphics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juulio.github.io"
# url: "http://localhost:4000"
twitter_username: juulio
github_username:  juulio

# Build settings
markdown: kramdown
