# Site settings

title: juulio.com # Title of your site
# email: your-email@domain.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  I write Computer Generated Graphics - Love Javascript + web + Openframeworks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juulio.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     juulio  # Replace this with your Twitter username
github_username:      juulio  # Replace this with your GitHub username
linkedin_username:    juliodelvalle  # Replace this with your LinkedIn username

# Build settings
markdown: kramdown
