# Site settings
title: juulio
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Costa Rica.<br />Software developer.<br />Computer Graphics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: juulio
github_username:  juulio

# Build settings
markdown: kramdown
