# Site settings
title: juulio @ github
description: This is the description
baseurl: "/jekyll-demo/" # the subpath of your site, e.g. /blog/
url: "http://juulio.github.io" # the base hostname & protocol for your site
twitter_username: juulio
github_username:  juulio

# Build settings
markdown: kramdown
